// <auto-generated />
using System;
using Encuesta.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Encuesta.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EncuestaDbContext))]
    [Migration("20260926095300_AddRespuestas")]
    partial class AddRespuestas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Encuesta.Domain.Entities.Encuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("EsAnonima")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("FechaLimite")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("RespuestaUnica")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Token")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreadorId");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasFilter("[Token] IS NOT NULL");

                    b.ToTable("Encuesta", (string)null);
                });

            modelBuilder.Entity("Encuesta.Domain.Entities.ItemRespuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RespuestaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("RespuestaId");

                    b.ToTable("ItemRespuesta", (string)null);
                });

            modelBuilder.Entity("Encuesta.Domain.Entities.OpcionPregunta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<Guid?>("PreguntaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.ToTable("OpcionPregunta", (string)null);
                });

            modelBuilder.Entity("Encuesta.Domain.Entities.Pregunta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EncuestaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsObligatoria")
                        .HasColumnType("bit");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EncuestaId");

                    b.ToTable("Pregunta", (string)null);
                });

            modelBuilder.Entity("Encuesta.Domain.Entities.RespuestaEncuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EncuestaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EnviadaEn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Huella")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("ParticipanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EncuestaId", "Huella")
                        .IsUnique()
                        .HasDatabaseName("IX_Respuesta_EncuestaId_Huella")
                        .HasFilter("[Huella] IS NOT NULL");

                    b.ToTable("Respuesta", (string)null);
                });

            modelBuilder.Entity("Encuesta.Domain.Entities.ItemRespuesta", b =>
                {
                    b.HasOne("Encuesta.Domain.Entities.RespuestaEncuesta", null)
                        .WithMany("Items")
                        .HasForeignKey("RespuestaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Encuesta.Domain.Entities.OpcionPregunta", b =>
                {
                    b.HasOne("Encuesta.Domain.Entities.Pregunta", null)
                        .WithMany("Opciones")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Encuesta.Domain.Entities.Pregunta", b =>
                {
                    b.HasOne("Encuesta.Domain.Entities.Encuesta", null)
                        .WithMany("Preguntas")
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Encuesta.Domain.Entities.RespuestaEncuesta", b =>
                {
                    b.HasOne("Encuesta.Domain.Entities.Encuesta", null)
                        .WithMany()
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Encuesta.Domain.Entities.Encuesta", b =>
                {
                    b.Navigation("Preguntas");
                });

            modelBuilder.Entity("Encuesta.Domain.Entities.Pregunta", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("Encuesta.Domain.Entities.RespuestaEncuesta", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
